### PR TITLE
Run-tests.sh: run create_admin with sudo if sudo exists

### LINKED ISSUE #568: run-tests.sh sudo command not found
### Describe the feature or problem you’d like to solve

`run-tests.sh` fails in Docker due to lack of sudo command

### Proposed solution

Run with sudo, only if sudo exists

### PR DESCRIPTION
**Pull request by xezpeleta**
fixes #568

### CODE REVIEW

**Comment by elacunza** [comment]
This will fail if sudo is not installed and launched with a regular user. Error will be "You have to be root to run this command", but it isn't advisable to run tests as root (temporary docker for tests is an exception).

If we check user id, and use sudo if not root, the error will be something like "sudo command not found" which would be more instructive... ¿?

**Comment by igorbga** [comment]
I think @xezpeleta is refering to docker container used for development and testing. isn't it?
So @xezpeleta, @elacunza why not just install sudo and configure it properly not to request password?

Obviously the production images should not ship with sudo but installing and configuring it for images used in CI seems a reasonable and easy compromise.

**Comment by elacunza** [comment]
Installing sudo in test docker image seems a good solution, too. It won't hurt having it in production image too, currently we're launching all with root privileges in docker image I think...?

**Comment by igorbga** [comment]
If we can skip adding it for production images better, just in case we forget about it in a future and we change the user in the container.
In fact I think that right now test and development images are not at all related to production images, isn't it @xezpeleta ? So this should be trivial. By the way, to be honest I think that CI image should be based in production image not in development image.

**Comment by xezpeleta** [comment]
Ok, I install sudo in test image, which should be based in prod image.

**Pull request closed without merging**
