### PR TITLE
Migrated to Symfony 2.8 

### PR DESCRIPTION
**Pull request by xezpeleta**
Elkarbackup changed to Symfony 2.8 (LTS, until Nov. 2018).

Deb package available here: https://github.com/xezpeleta/elkarbackup/releases/download/elkarbackup_1.2.0-Pre-Alpha1/elkarbackup_1.2.0-Pre-Alpha1_all.deb

### CODE REVIEW

**Comment by antton** [comment]
Christmas edition! ;) well done!

**Comment by parreitu** [comment]
Oso ona !!!

2015-12-15 7:15 GMT+01:00 Antton Rodriguez <notifications@github.com>:

> Christmas edition! ;) well done!
>
>
>

**Comment by xezpeleta** [comment]
By the way, @adrianles could you try mixing this PR with your Tahoe project fork to see if everything works ok?

If you prefer, here you have a DEB package:
https://github.com/xezpeleta/elkarbackup/releases/download/elkarbackup_1.2.0-Pre-Alpha1/elkarbackup_1.2.0-Pre-Alpha1_all.deb

I'd like to know what's the easiest way to merge both forks. I'm not sure what's the best order, so I won't merge this PR with the master by the moment.

@elacunza @antton

**Comment by adrianles** [comment]
I've just submitted the PR for the Tahoe fork #118. I'm willing to take any advice or recommendation.
If everything is ok, we could apply the Symfony upgrade after the Tahoe version and have both ready for the 1.2 release, but that is up to you.

I've also checked the diffs between both PRs and there are some conflicts but I don't think there's going to be any real trouble.

@xezpeleta @elacunza

**Comment by xezpeleta** [comment]
Nice! I'll check it tonight!
2015 abe. 15 3:00 PM erabiltzaileak hau idatzi du ("Adrián" <
notifications@github.com>):

**Pull request closed without merging**
