### PR TITLE
Docker image for tests

### PR DESCRIPTION
**Pull request by xezpeleta**
This PR adds a docker environment for tests.

It points to production Dockerfile (/docker/Dockerfile). The codebase is mounted as volume and it uses a custom entrypoint.

Advantages:
- Easy to use: docker-compose up, docker-compose down, etc
- Faster, as the volume is mounted and you don't need to build the image every time...

Downsides:
- It's not exactly like the production image: as we're replacing /app/elkarbackup dir and we need to repeat some commands in the entrypoint.

This is my second approach. First I tried an alternative way, using the production image as base layer in a custom-simple Dockerfile where I install the dependencies. The entrypoint just runs the tests script.

It was perfect for automated CI, but it's not very comfortable for manual executions...

Alternative version: https://github.com/xezpeleta/elkarbackup/tree/docker-test/docker/test

### CODE REVIEW

**Comment by elacunza** [comment]
This approach won't catch a missing .php for example, because it doesn't use elkarbackup version in production image but only the environment in it. I think you alternative approach is better.

For fast tests without building docker image, developer can ./run-tests.sh directly and it will use local development environment (I'm doing it myself these days).

**Comment by elacunza** [comment]
Have you considered creating a "run-tests.sh" command in prod image, so that for launching tests it would be just build prod image, docker-compose up it, and the docker exec -it testcontainer /run-tests.sh" or something like that?

I wouldn't mind shipping automated tests in prod image, that way users can launch them too (for example with a different DB server) and it won't take much space really...

**Comment by igorbga** [comment]
But for tests we need sudo, isn't it? Rather not have it in prod.

**Comment by xezpeleta** [comment]
We shiuld install sudo, git, zip and composer in prod image

igorbga ***@***.***> igorleak hau idatzi zuen (2021 mai. 20,
og. 17:12):

**Comment by elacunza** [comment]
I don't see a problem with sudo in prod image.
Why do we need git, zip and composer for running tests? I don't see them used in the scripts... ¿?

**Comment by xezpeleta** [comment]
>  Why do we need git, zip and composer for running tests? I don't see them used in the scripts... ¿?

You're right, my fault.

Executing the run-tests.sh with incorrect envars I got the error `sh: 1: composer: not found` and that's why I thought composer was required (and therefore git and zip).

```
In EnvVarProcessor.php line 171:
                                                                
  Environment variable not found: "SYMFONY__DATABASE__DRIVER".  
                                                                

hautelook:fixtures:load [-b|--bundle [BUNDLE]] [--no-bundles [NO-BUNDLES]] [-m|--manager MANAGER] [--append] [--shard SHARD] [--purge-with-truncate] [-h|--help] [-q|--quiet] [-v|vv|vvv|--verbose] [-V|--version] [--ansi] [--no-ansi] [-n|--no-interaction] [-e|--env ENV] [--no-debug] [--] <command>

sh: 1: composer: not found
sh: 1: composer: not found
```


> Have you considered creating a "run-tests.sh" command in prod image, so that for launching tests it would be just build prod image, docker-compose up it, and then docker exec -it testcontainer /run-tests.sh" or something like that?

That could be a simple solution!

Something like that?

**Dockerfile**
```
...
COPY run-tests.sh /
RUN chmod +x /run-tests.sh
...
```

**/run-tests.sh**
```bash
#!/bin/bash

source /envars.sh

export APP_ENV=test
export DATABASE_HOST="${DATABASE_HOST:=db}"
export DATABASE_PORT="${DATABASE_PORT:=3306}"
export DATABASE_NAME="${DATABASE_NAME:=elkarbackuptests}"
export DATABASE_USER="${DATABASE_USER:=root}"
export DATABASE_PASSWORD="${DATABASE_PASSWORD:=your-password-here}"

# Run tests
cd /app/elkarbackup/
./run-tests.sh
``` 

And then the CI could do the following:

```sh
docker-compose up
docker-compose exec elkarbackup /run-tests.sh
# capture the exit code of previous command...
docker-compose down
```

I'm gonna do some tests and see if it works well and update the PR (or open a new one...).

**Comment by xezpeleta** [comment]
Well, probably better if we add the test environment variables in envar.sh file.

**Comment by elacunza** [comment]
Yes, if that can be done in CI, just setting test values in test docker-compose.yml should be enough?

**Comment by xezpeleta** [comment]
Update:

The command `docker up -d` ends before having the stack up and ready. We cannot execute _run-tests.sh_ immediately.

I am trying to call `/entrypoint.sh` from `/run-tests.sh`. This way when we execute the command we are sure everything is ready. It works in local but not in CI.

```
...
elkarbackup-test_1  | Created database `elkarbackuptests` for connection named default
elkarbackup-test_1  | [notice] Migrating up to DoctrineMigrations\Version20210315133526
elkarbackup-test_1  | [notice] finished in 760.6ms, used 26M memory, 30 migrations executed, 102 sql queries
elkarbackup-test_1  | 
elkarbackup-test_1  | sh: 1: composer: not found
elkarbackup-test_1  | sh: 1: composer: not found
test_elkarbackup-test_1 exited with code 127
Stopping test_db_1               ... 
Stopping test_db_1               ... done
127
Aborting on container exit...
Error: Process completed with exit code 127.
```

I will continue tomorrow :cry:

**Comment by elacunza** [comment]
What about entrypoint.sh recognizing a ELKARBACKUP_RUN_TEST envvar? If that is set, then leave apache as background process and run tests?

**Comment by xezpeleta** [comment]
Yes, I was thinking on that too.

By the way, I discovered a bug that should be fixed before: #576

**Comment by xezpeleta** [comment]
I have made some progress. 

I can confirm `composer` is required. If I don't include it, it works on my local environment but Github Action doesn't like it (don't ask me why):

image

After adding it to the prod image, everything is ok:

https://github.com/xezpeleta/elkarbackup/runs/3050508053?check_suite_focus=true

Thanks

**Comment by xezpeleta** [comment]
What do you think @elacunza ? Does it make sense? Or should we avoid installing composer in the production image?

**Comment by elacunza** [comment]
I don't think we'll be using the command in production, but doesn't seem to be a problem either. Are git and zip packages dependencies needed for compose?

**Comment by xezpeleta** [comment]
> Are git and zip packages dependencies needed for compose?

Yes.

> I don't think we'll be using the command in production, but doesn't seem to be a problem either

Thank you. I will squash and merge this PR.

**Comment by elacunza** [comment]
Ondo!

**Pull request merged**
