### PR TITLE
Empty script's lists before adding the new ones (fixes issue #512)

### PR DESCRIPTION
**Pull request by uanabitarte**
The scripts were not been removed before adding the new ones

### CODE REVIEW

**Comment by elacunza** [comment]
API should return an error if an incorrect script ID is requested for adding to a client?

**Comment by uanabitarte** [comment]
Yes, it should throw an exception if the script does not exist or it is not suitable for that action (for example, if it is not a client post script)

**Comment by elacunza** [comment]
Yes sorry, I haven't seen that part of the file this morning.
Please check the previous comment so we can merge this.
You may consider to change script var to scriptId, and also result var to script, which would be much cleaner. If you do so, please use a separate "style only" PR, thanks :)

**Comment by uanabitarte** [comment]
I have removed the type, so I will make the style changes later in another PR

**Pull request merged**
